### ISSUE TITLE
HDF5 and JLD

### ISSUE THREAD

**Issue by iceblue25** [JuliaIO/JLD.jl#38]
I want to use this module but I dont have the option to have/install HDF5. It seems that by default HDF5 is installed with this module and depends on it. A past commit states that HDF5 is not needed. 

Is it just a matter of using the HDF5 module but not necessary?
Is there a clean solution to avoid downloading and building HDF5 dependancies?

**Comment by timholy** [comment]
No, you need HDF5. I'm not sure what commit you're referring to.

If you can't install HDF5, it would be fantastic to have someone push https://github.com/JuliaLang/HDF5.jl/pull/152 over the finish line and contribute the result back.

**Comment by iceblue25** [comment]
Thanks for the link. I was referring to the title of this https://github.com/JuliaLang/JLD.jl/commit/e965bd56e9629ab04c577418b155ea524eaec20a

"Update doc: HDF5 import no longer necessary"

**Comment by timholy** [comment]
That just means that as a user you don't have to say `using HDF` before `using JLD`. Formerly, you had to do that because JLD lived in the HDF5 repository, so Pkg didn't know where to find JLD. Now that JLD lives in its own separate repo, that's no longer needed.

The JLD package [still uses HDF5 internally](https://github.com/JuliaLang/JLD.jl/blob/b6fde7bda002d7f509c540a07a81ba4a95150a58/src/JLD.jl#L8).

**Comment by tkelman** [comment]
Could also try using Conda.jl as an optional binary provider of libhdf5, if they have a new enough version.

**Comment by timholy** [comment]
Whatever you figure out, please do report back or submit a PR---would be great to have this more generally available.

**Comment by iceblue25** [comment]
Thanks, I think I will try to build hdf5 from scratch and see where that gets me since I get the advantages of hdf5
